language: python
sudo: false
cache: pip

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-django22
    - python: 3.6
      env: TOXENV=py36-django22
    - python: 3.7
      env: TOXENV=py37-django22
    - python: 3.8
      env: TOXENV=py38-django22
    - python: 3.9-dev
      env: TOXENV=py39-django22
    - python: 3.6
      env: TOXENV=py36-django30
    - python: 3.7
      env: TOXENV=py37-django30
    - python: 3.8
      env: TOXENV=py38-django30
    - python: 3.9-dev
      env: TOXENV=py39-django30
    - python: 3.6
      env: TOXENV=py36-django31
    - python: 3.7
      env: TOXENV=py37-django31
    - python: 3.8
      env: TOXENV=py38-django31
    - python: 3.9-dev
      env: TOXENV=py39-django31
    # Adding jobs for ppc64le
    - python: 3.5
      env: TOXENV=py35-django22
      arch: ppc64le
    - python: 3.6
      env: TOXENV=py36-django22
      arch: ppc64le
    - python: 3.7
      env: TOXENV=py37-django22
      arch: ppc64le
    - python: 3.8
      env: TOXENV=py38-django22
      arch: ppc64le
    - python: 3.9-dev
      env: TOXENV=py39-django22
      arch: ppc64le
    - python: 3.6
      env: TOXENV=py36-django30
      arch: ppc64le
    - python: 3.7
      env: TOXENV=py37-django30
      arch: ppc64le
    - python: 3.8
      env: TOXENV=py38-django30
      arch: ppc64le
    - python: 3.9-dev
      env: TOXENV=py39-django30
      arch: ppc64le
    - python: 3.6
      env: TOXENV=py36-django31
      arch: ppc64le
    - python: 3.7
      env: TOXENV=py37-django31
      arch: ppc64le
    - python: 3.8
      env: TOXENV=py38-django31
      arch: ppc64le
    - python: 3.9-dev
      env: TOXENV=py39-django31
      arch: ppc64le

install:
  - pip install tox

script:
  - tox

notifications:
  email:
    recipients:
      - niwi@niwi.nz
    on_success: change
    on_failure: change
